function renderAbout() {
    document.querySelector('.page-CSS').innerHTML = `
    <link rel="stylesheet" href="./css/info.css">
    `
    document.querySelector('#page').innerHTML = `
    <p>Man bun cardigan palo santo paleo, pinterest squid raclette reprehenderit grailed glossier man braid pitchfork snackwave PBR&B. In pinterest mustache, meh Brooklyn plaid lumbersexual crucifix tbh enamel pin. Dolore officia lomo food truck, tempor ex microdosing next level wayfarers franzen ugh. Kogi blackbird spyplane ea eu. Big mood affogato selvage humblebrag cliche. Aliquip paleo big mood irony yr.</p>
    <p>Dreamcatcher dolore mlkshk twee disrupt polaroid blue bottle photo booth culpa. Adipisicing cliche dolore artisan pinterest unicorn before they sold out fugiat bicycle rights nostrud etsy beard. Meh man bun lomo pabst franzen eiusmod. Magna bushwick bespoke pitchfork cillum laboris direct trade YOLO reprehenderit consequat. Hexagon ut sint everyday carry cred twee do squid mlkshk hoodie.</p>
    <p>Est flannel in la croix praxis adaptogen, austin thundercats tempor. Pork belly skateboard asymmetrical cliche. Four loko ascot fixie 90's tbh DIY, truffaut ipsum woke. Succulents try-hard whatever tattooed.</p>
    <p>Ennui fashion axe chartreuse, iceland laborum qui pickled iPhone swag adaptogen. Fugiat enamel pin yuccie waistcoat. Artisan aesthetic blackbird spyplane, raclette crucifix velit distillery tote bag kombucha aliquip. Eu cupidatat flannel, chillwave meh marfa snackwave et lo-fi listicle pinterest.</p>
    <p>Grailed banjo XOXO master cleanse. Paleo tumeric duis, do poke in af 90's umami before they sold out shaman mustache pour-over. +1 gochujang gluten-free, ipsum narwhal mukbang cillum consectetur jean shorts laboris synth chicharrones post-ironic. Kombucha bodega boys blackbird spyplane, ethical af ut reprehenderit keffiyeh nisi. Dolor art party deserunt poutine marfa, bitters flexitarian cupping succulents.</p>
    Marxism succulents thundercats raw denim artisan sunt squid proident organic. Farm-to-table pariatur kogi, live-edge bushwick kombucha taxidermy church-key sus in. Woke church-key you probably haven't heard of them tilde waistcoat keffiyeh neutral milk hotel bitters locavore glossier. Tacos activated charcoal marxism, excepteur franzen af knausgaard sustainable intelligentsia waistcoat. Chartreuse keffiyeh consectetur blue bottle dolore. Trust fund pabst migas pour-over, williamsburg iPhone 3 wolf moon JOMO.
    <p>Tousled tempor nulla jawn kinfolk DIY. Enim tumeric chillwave truffaut. Raw denim trust fund dreamcatcher pitchfork dolore cillum seitan cupidatat. Hell of cred adaptogen, salvia irony cronut ascot kale chips copper mug plaid literally bicycle rights scenester waistcoat do. Fugiat before they sold out freegan heirloom pitchfork lorem post-ironic meh. Master cleanse small batch aesthetic, ea freegan id vice four dollar toast biodiesel sunt.</p>
    <p>Consectetur aliqua semiotics, schlitz palo santo ennui seitan snackwave stumptown edison bulb dreamcatcher. Paleo ugh in wayfarers ut schlitz knausgaard migas aliquip banjo tumeric raw denim kickstarter you probably haven't heard of them master cleanse. Quis cronut chia fixie jean shorts ullamco dreamcatcher craft beer aesthetic. Consectetur live-edge succulents jawn id celiac letterpress pop-up green juice offal direct trade vegan kinfolk distillery kitsch.</p>
    <p>Sus +1 palo santo poutine kale chips nisi, viral cardigan meditation same. Raclette thundercats commodo craft beer. Skateboard et coloring book hoodie leggings. 90's mukbang prism marfa, keffiyeh same whatever chia marxism tumeric. Pitchfork irure nostrud prism, jianbing godard XOXO kale chips ipsum sint farm-to-table.</p>
    <p>Biodiesel blog gastropub venmo sartorial cronut. DSA cornhole shoreditch ad. DSA tempor air plant sustainable adipisicing VHS gentrify meh whatever semiotics knausgaard jean shorts. Chia ramps tbh polaroid excepteur truffaut. Art party butcher drinking vinegar ex. Dolore listicle deep v ut poutine bruh readymade artisan actually copper mug helvetica.</p>
    `
}